feat: update person detection to GA
googleapis/java-video-intelligence pull request #344
Opened 2020-12-03 02:13 UTC by telpirion

This PR does the following:

* Updates the person detection samples to use the v1 version of the service.
* Removes the `_beta` from the region tags
* Moves samples and tests out of the beta.* namespaces

2020-12-03 23:28 UTC, munkhuushmgl approved these changes

2020-12-08 17:14 UTC, chingor13 requested changes

2020-12-08 17:14 UTC, chingor13 commented on samples/snippets/src/main/java/com/example/video/DetectPerson.java
> +package com.example.video;
We should avoid `com.example` except for legacy samples, let's not move these into `com.example`.

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md#package-names

2020-12-08 19:24 UTC, chingor13 approved these changes

2020-12-08 20:59 UTC, merged